import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Press_Start_2P } from "next/font/google"
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

const pressStart = Press_Start_2P({
    display: 'swap',
    weight: '400'
})

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${pressStart.className}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
